#!/usr/bin/env python3
import concurrent.futures
import sys
import socket
import struct

HOST = "127.0.0.1"
PORT = 58477

def client2(filename):
    try:
        with open(filename, 'r') as file:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.connect((HOST, PORT))
                s.sendall(struct.pack("!i", 1))  # Invia un segnale di tipo B (1)

                for line in file:
                    s.sendall(struct.pack("!i", len(line)))  # Invia la lunghezza 
                    s.sendall(line.encode())
                s.sendall(struct.pack("!I", 0))

    except FileNotFoundError:
        print(f"File non trovato: {filename}")
    except Exception as e:
        print(f"Errore nell'invio del file: {str(e)}")

def main():
    if len(sys.argv) < 2:
        print("Utilizzo: python3 client2.py file1.txt [file2.txt ...]")
        return

    with concurrent.futures.ThreadPoolExecutor(max_workers=len(sys.argv) - 1) as executor:
        for file in sys.argv[1:]:
            executor.submit(client2, file)

if __name__ == "__main__":
    main()

    
            

